FROM node:22-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG SUPABASE_DB_POOLER_URL
ARG UPSTASH_REDIS_REST_URL
ARG UPSTASH_REDIS_REST_TOKEN
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ARG EXA_API_KEY
ARG CLADO_API_KEY
ARG COMPOSIO_API_KEY
ARG ENCRYPTION_MASTER_KEY
ARG CRON_SECRET
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN NEXT_PUBLIC_SUPABASE_URL="$NEXT_PUBLIC_SUPABASE_URL" \
    NEXT_PUBLIC_SUPABASE_ANON_KEY="$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
    SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
    SUPABASE_DB_POOLER_URL="$SUPABASE_DB_POOLER_URL" \
    UPSTASH_REDIS_REST_URL="$UPSTASH_REDIS_REST_URL" \
    UPSTASH_REDIS_REST_TOKEN="$UPSTASH_REDIS_REST_TOKEN" \
    OPENAI_API_KEY="$OPENAI_API_KEY" \
    ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
    EXA_API_KEY="$EXA_API_KEY" \
    CLADO_API_KEY="$CLADO_API_KEY" \
    COMPOSIO_API_KEY="$COMPOSIO_API_KEY" \
    ENCRYPTION_MASTER_KEY="$ENCRYPTION_MASTER_KEY" \
    CRON_SECRET="$CRON_SECRET" \
    npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000

# Keep full install (including dev deps) because worker runtime uses ts-node.
COPY --from=builder /app ./

EXPOSE 3000
CMD ["npm", "run", "start"]
